export interface SetupInstantlyRequest {
  // Order context
  order_id: string;

  // Email for Instantly account (generated by n8n)
  instantly_email: string;

  // Credit card info (passed through, not stored)
  card_number: string;
  card_expiry: string; // MM/YY format
  card_cvc: string;
  card_name?: string;
  billing_zip?: string;

  // Client info
  client_email: string; // Email to invite as admin

  // Email credentials for verification
  imap_host: string;
  imap_user: string;
  imap_password: string;

  // Optional callback URL
  callback_url?: string;
}

export interface SetupInstantlyResponse {
  success: boolean;

  // On success
  instantly_email?: string;
  instantly_password?: string;
  instantly_api_key?: string;
  affiliate_verified?: boolean;

  // On failure
  error?: string;
  error_code?: ErrorCode;
  screenshot_url?: string;
  step_failed?: string;
}

export type ErrorCode =
  | "VALIDATION_ERROR"
  | "SIGNUP_FAILED"
  | "VERIFICATION_TIMEOUT"
  | "VERIFICATION_FAILED"
  | "PAYMENT_FAILED"
  | "COUPON_FAILED"
  | "API_KEY_FAILED"
  | "ADMIN_INVITE_FAILED"
  | "TIMEOUT"
  | "BROWSER_ERROR"
  | "INTERNAL_ERROR";

export interface AutomationStep {
  name: string;
  description: string;
  execute: () => Promise<void>;
}

export interface ImapConfig {
  host: string;
  port: number;
  user: string;
  password: string;
  tls: boolean;
}

export interface VerificationEmail {
  code: string;
  receivedAt: Date;
}
